include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  exclude:
    - lib/models/**/*.g.dart
    - lib/models/**/*.freezed.dart
    - lib/models/*.g.dart
    - lib/models/*.freezed.dart